spring.application.name=urlshortener
server.port=8080
app.base-url=http://localhost:8080


#mysql
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener
spring.datasource.username = root
spring.datasource.password = 111111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#JAP/ hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache TTL (how long URLs stay in cache)
app.cache.ttl-minutes=60


app.rate-limit.max-requests=10
app.rate-limit.window-minutes=1

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

app.click-flush.interval-ms=300000