# Dev Profile ? extra logging, show SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.shortTo.urlshortener=DEBUG
app.rate-limit.max-requests=100
app.click-flush.interval-ms=10000